data_local: null
data_remote: "emarro/clinvar_vep_512" #"emarro/maize-allele-frequency-20k-val"
repeat_weight: 0.1
num_workers: 1
eval_interval: "1ep"
seq_len: 512
target: "AUROC"
label: "clinvar"
log_only_N: 100
save_dir: "${paths.output_dir}/boundaries/${eval_dataset.label}/"  #folder to save outputs to
