data_local: null
data_remote: "emarro/maize_maf_with_annot_20k" #"emarro/maize-allele-frequency-20k-val"
repeat_weight: 0.1
num_workers: 1
eval_interval: "1ep"
seq_len: 512
target: "PearsonCorrCoef"
label: "maize_allele_freq"
