disable_hf: False
save_local: False
save_to_hub: True
private: True
hub_repo_id: "emarro/test-hnet-upload"
save_interval: "250ba"
save_folder: "${paths.output_dir}/checkpoints/hf/" # e.g. './{run_name}/ckpt' (local) or 's3://mybucket/mydir/{run_name}/ckpt' (remote)

