"""
Parse an arbitrary fasta file into a HF dataset with fields chr, seq, and pos
Generated by ChatGPT
"""

import argparse
from datasets import Dataset, DatasetDict
from Bio import SeqIO
from tqdm import tqdm


def chunk_sequence(seq, seq_len, overlap):
    step = seq_len - overlap
    if step <= 0:
        raise ValueError("overlap must be smaller than seq_len")

    for start in range(0, len(seq) - seq_len + 1, step):
        yield start, seq[start : start + seq_len]


def main(args):
    val_contigs = set(args.val_contigs.split(","))
    print(f"Using {val_contigs} as val contigs")

    train_records = []
    val_records = []

    for record in tqdm(SeqIO.parse(args.fasta, "fasta")):
        contig = record.id
        desc = record.description
        if args.primary_only:
            raise NotImplementedError(
                "Filterint for only primary contigs not implemented atm"
            )
        seq = str(record.seq)

        target = (
            val_records
            if any(
                [val_contig in desc for val_contig in val_contigs]
            )  # search in desc, lacking id map
            else train_records
        )

        for start, chunk in chunk_sequence(seq, args.seq_len, args.overlap):
            if (
                chunk.count("N") > args.seq_len * args.n_perc
            ):  # leave out sequences with too many "N"s
                continue
            target.append(
                {
                    "chr": contig,
                    "pos": start,  # 0-based start position
                    "seq": chunk,
                }
            )

    dataset = DatasetDict(
        {
            "train": Dataset.from_list(train_records),
            "validation": Dataset.from_list(val_records),
        }
    )
    print(dataset)

    dataset.save_to_disk(args.out_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--fasta", required=True, help="Input FASTA file")
    parser.add_argument("--seq-len", type=int, required=True, help="Sequence length")
    parser.add_argument("--overlap", type=int, default=0, help="Sequence overlap")
    parser.add_argument(
        "--n-perc",
        type=float,
        default=0.25,
        help="Maximum allowable percentage of Ns in seq",
    )
    parser.add_argument(
        "--val-contigs",
        required=True,
        help="Comma-separated contig IDs for validation (e.g. 1,2)",
    )
    parser.add_argument("--out-dir", required=True, help="Output dataset directory")
    parser.add_argument(
        "--primary-only",
        required=False,
        action="store_true",
        help="Ignore non primary contigs",
    )

    args = parser.parse_args()
    main(args)
