_target_: wrappers.hnet.build_model
_convert_: "all"
_modelstr_: "cnet_exp_${model.arch_layout}_N=${model.default_target_ratio}_D=${model.d_model}_a=${model.alpha}_b={model.beta}"

arch_layout: ["c3t1",["C15"],"c4"] #architecture for DNA from Table 7 with best PPL in HNet paper
d_model: [1024, 1024] #d_model of each stage (matches stages from arch_layout)
d_intermediate: [1024, 1536] # size of FFN sizes corresponding to above
vocab_size: 16

# Optimal selection hyperparams
selection: "os"
alpha: 0.955
beta: 0.1

ssm_cfg:
  chunk_size: 256
  d_conv: 4
  d_state: 128
  expand: 2
attn_cfg:
  num_heads: [8, 8]
  rotary_emb_dim: [16, 32]
  window_size: [511, -1]
tie_embeddings: False

pad_token_id: -100  # [PAD] token ID
ratio_loss_weight: 0.00 #alpha from the paper
use_return_dict: False

# Meta variables, not used in HNetConfig directly
default_target_ratio: 3
max_seq_len: 512
mlm: True
log_bpreds: True
